<a href="https://colab.research.google.com/github/rk119/F20BC/blob/main/Copy_of_F20BC_CW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Imports

In [134]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

### Load the data

In [3]:
df  = pd.read_csv("/content/drive/MyDrive/F20BC-Dataset/data_banknote_authentication.csv")

### View the first 5 instances of the data

In [4]:
df.head()

3.6216  8.6661  -2.8073  -0.44699  0
0  4.54590  8.1674  -2.4586  -1.46210  0
1  3.86600 -2.6383   1.9242   0.10645  0
2  3.45660  9.5228  -4.0112  -3.59440  0
3  0.32924 -4.4552   4.5718  -0.98880  0
4  4.36840  9.6718  -3.9606  -3.16250  0

In [5]:
df.shape

(1371, 5)

In [6]:
# if len(df.columns) == 1:
#     # Split the single column into multiple columns by the comma delimiter
#     df = df.iloc[:, 0].str.split(',', expand=True)

# # Convert the split columns to numeric types
# df = df.apply(pd.to_numeric)

# Check if there are 5 columns
if df.shape[1] == 5:
    # Split into features (X) and label (Y)
    X = df.iloc[:, :-1]
    Y = df.iloc[:, -1]

# Convert X and Y to numpy arrays
X_array = X.to_numpy()
Y_array = Y.to_numpy()

In [7]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
1366    1
1367    1
1368    1
1369    1
1370    1
Name: 0, Length: 1371, dtype: int64

In [8]:
Y_array

array([0, 0, 0, ..., 1, 1, 1])

In [9]:
X

3.6216    8.6661  -2.8073  -0.44699
0     4.54590   8.16740  -2.4586  -1.46210
1     3.86600  -2.63830   1.9242   0.10645
2     3.45660   9.52280  -4.0112  -3.59440
3     0.32924  -4.45520   4.5718  -0.98880
4     4.36840   9.67180  -3.9606  -3.16250
...       ...       ...      ...       ...
1366  0.40614   1.34920  -1.4501  -0.55949
1367 -1.38870  -4.87730   6.4774   0.34179
1368 -3.75030 -13.45860  17.5932  -2.77710
1369 -3.56370  -8.38270  12.3930  -1.28230
1370 -2.54190  -0.65804   2.6842   1.19520

[1371 rows x 4 columns]

In [10]:
X_array

array([[  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       [  3.4566 ,   9.5228 ,  -4.0112 ,  -3.5944 ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_normalized = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

In [12]:
df_normalized

3.6216    8.6661   -2.8073  -0.44699    0
0     0.835659  0.820982  0.121804  0.644326  0.0
1     0.786629  0.416648  0.310608  0.786951  0.0
2     0.757105  0.871699  0.054921  0.450440  0.0
3     0.531578  0.348662  0.424662  0.687362  0.0
4     0.822859  0.877275  0.057100  0.489711  0.0
...        ...       ...       ...       ...  ...
1366  0.537124  0.565855  0.165249  0.726398  1.0
1367  0.407690  0.332868  0.506753  0.808350  1.0
1368  0.237385  0.011768  0.985603  0.524755  1.0
1369  0.250842  0.201701  0.761587  0.660675  1.0
1370  0.324528  0.490747  0.343348  0.885949  1.0

[1371 rows x 5 columns]

In [13]:
if len(df_normalized.columns) == 1:
    # Split the single column into multiple columns by the comma delimiter
    df_normalized = df_normalized.iloc[:, 0].str.split(',', expand=True)

# Convert the split columns to numeric types
df_normalized = df_normalized.apply(pd.to_numeric)

# Check if there are 5 columns
if df_normalized.shape[1] == 5:
    # Split into features (X) and label (Y)
    X_norm = df_normalized.iloc[:, :-1]
    Y_norm = df_normalized.iloc[:, -1]

# Convert X and Y to numpy arrays
X_array_norm = X_norm.to_numpy()
Y_array_norm = Y_norm.to_numpy()

In [14]:
X_array_norm

array([[0.83565902, 0.82098209, 0.12180412, 0.64432563],
       [0.78662859, 0.41664827, 0.31060805, 0.78695091],
       [0.75710505, 0.87169921, 0.05492063, 0.45043964],
       ...,
       [0.23738543, 0.01176814, 0.98560321, 0.52475518],
       [0.25084193, 0.20170105, 0.76158701, 0.6606745 ],
       [0.32452819, 0.49074676, 0.34334762, 0.88594888]])

In [15]:
len(X_array)

1371

In [16]:
len(Y_array)

1371

# Functions

### Activation Functions

In [80]:
class ActivationFunctions:
  def evaluate(self,x):
    pass
  def derivate(self,x):
    pass

class Identity:
  def evaluate(self,x):
    return x
  def derivative(self,x):
    return 1

class Sigmoid(ActivationFunctions):
  def evaluate(self,x):
    x_clipped = np.clip(x, -500, 500)
    return 1 / (1 + np.exp(-x_clipped))
  def derivative(self,x):
    f = self.evaluate(x)
    return f * (1-f)

class Tanh(ActivationFunctions):
  def evaluate(self,x):
    return np.tanh(x)
  def derivative(self,x):
    f = self.evaluate(x)
    return 1 - f ** 2

class relu(ActivationFunctions):
  def evaluate(self,x):
    return np.maximum(0, x)
  def derivative(self,x):
    return (x > 0).astype(float)

### Loss Functions

In [18]:
class LossFunctions:
  def evaluate(self,x):
    pass
  def derivate(self,x):
    pass

# y is predictions made by the neural network
# t is target/actual numbers corresponding to inputs
class Mse(LossFunctions):
  def evaluate(self, y, t):
    return ((t - y) ** 2).mean()
  def derivative(self, y, t):
    return 2 * (y - t) / len(y)

class BinaryCrossEntropy(LossFunctions):
  def evaluate(self, y, t):
    y_pred = np.clip(y, 1e-7, 1 - 1e-7)
    term0 = (1 - t) * np.log(1 - y_pred + 1e-7)
    term1 = t * np.log(y_pred + 1e-7)
    return - (term0 + term1).mean()

  def derivative(self, y, t):
    y_pred = np.clip(y, 1e-7, 1 - 1e-7)
    return (t / y_pred) - (1 - t) / (1 - y_pred)

class Hinge(LossFunctions):
  def evaluate(self, y, t):
    return np.maximum(0, 1 - t * y).mean()

  def derivative(self, y, t):
    return np.where(t * y < 1, -t, 0)

# Neural Network

In [135]:
class InputLayer:
    def __init__(self, input_size):
        self.nb_nodes = input_size

    def forward(self, input_data):
        return input_data

class Layer:
    def __init__(self, input_size, nodes, activation, weights=None, biases=None):
        self.nb_nodes = nodes
        self.W = weights if weights is not None else np.random.randn(input_size, nodes)
        self.B = biases if biases is not None else np.random.randn(nodes)
        self.activation = activation

    def forward(self, input_data):
        self.X_in = input_data
        z = np.dot(input_data, self.W) + self.B
        out = self.activation.evaluate(z)
        return out

class NeuralNetwork:
    def __init__(self, configuration, position=None):
        self.layers = []
        input_size = configuration[0]

        # The input layer is simply added as a pass-through layer
        self.layers.append(InputLayer(input_size))

        # If a position vector is provided, it contains weights and biases for each layer
        if position is not None:
            for idx, (nodes, activation) in enumerate(configuration[1:]):
                weights, biases = position[idx]
                # print("layer ", idx, "W = ",weights, "B = ", biases )
                layer = Layer(input_size, nodes, activation, weights=weights, biases=biases)
                self.add(layer)
                input_size = nodes  # Update input size for the next layer
        else:
            # If no position vector, initialize layers with random weights and biases
            for nodes, activation in configuration[1:]:
                layer = Layer(input_size, nodes, activation)
                self.add(layer)
                input_size = nodes  # Update input size for the next layer

    def add(self, layer):
        self.layers.append(layer)

    def forward(self, input_data):
        for layer in self.layers:
            input_data = layer.forward(input_data)
        return input_data

    def print_layers(self):
        for i, layer in enumerate(self.layers):
            if isinstance(layer, InputLayer):
                print(f"Layer {i}: Input Layer with {layer.nb_nodes} nodes")
            elif isinstance(layer, Layer):
                print(f"Layer {i}: Hidden Layer with {layer.nb_nodes} nodes, Activation Function: {layer.activation.__class__.__name__}")
                print(f"  Weights Shape: {layer.W.shape}, Biases Shape: {layer.B.shape}")
                print(f"  Weights= : {layer.W}, Biases= {layer.B}")
            else:
                print(f"Layer {i}: Unknown Layer Type")

    def flatten_weights_and_biases(self):
        flattened_vector = []
        for layer in self.layers:
            if isinstance(layer, Layer):
                # Flatten and append weights and biases of this layer
                flattened_weights = layer.W.flatten()
                flattened_biases = layer.B.flatten()
                flattened_vector.extend(flattened_weights.tolist())
                flattened_vector.extend(flattened_biases.tolist())
        return flattened_vector

In [136]:
def unflatten_weights_and_biases(flattened_vector, configuration):
    position = []
    index = 0

    # Skip the input layer configuration, as it doesn't have weights or biases
    for nodes, _ in configuration[1:]:
        # Previous layer's node count is the number of rows for weights
        input_size = configuration[0] if not position else position[-1][0].shape[1]

        # Calculate the number of weights and biases
        num_weights = input_size * nodes
        num_biases = nodes

        # Extract weights and biases from the flattened vector
        weights = flattened_vector[index : index + num_weights]
        biases = flattened_vector[index + num_weights : index + num_weights + num_biases]

        # Reshape weights to the correct dimensions and add to position
        position.append((np.array(weights).reshape(input_size, nodes), np.array(biases)))

        # Update the index
        index += num_weights + num_biases

    return position

In [137]:
relu_activation = relu()
sigmoid_activation = Sigmoid()
tanh_activation = Tanh()

In [138]:
config = [
    4,
    [3, relu_activation],
    [4, sigmoid_activation],
    [1, sigmoid_activation]
]

In [139]:
nn = NeuralNetwork(config)

In [140]:
nn.print_layers()

Layer 0: Input Layer with 4 nodes
Layer 1: Hidden Layer with 3 nodes, Activation Function: relu
  Weights Shape: (4, 3), Biases Shape: (3,)
  Weights= : [[ 0.93989367  0.3976655  -1.47762945]
 [ 0.66932266  0.17562002  1.0020521 ]
 [ 0.49218396 -0.23054714  1.01347537]
 [ 2.03593786  1.31941714 -0.20246344]], Biases= [-0.93509639 -1.49355339  0.1928472 ]
Layer 2: Hidden Layer with 4 nodes, Activation Function: Sigmoid
  Weights Shape: (3, 4), Biases Shape: (4,)
  Weights= : [[-0.44063983  0.23283755 -1.46603731 -0.40048528]
 [ 0.32923053 -0.33046873 -0.62540743 -2.56661931]
 [-0.05183713 -0.91995416  0.77025599 -0.88356167]], Biases= [ 0.29705918 -0.30992527  0.32996834 -0.16612142]
Layer 3: Hidden Layer with 1 nodes, Activation Function: Sigmoid
  Weights Shape: (4, 1), Biases Shape: (1,)
  Weights= : [[ 0.65658107]
 [ 0.72059253]
 [-0.42121166]
 [ 2.02873371]], Biases= [0.27294735]


In [141]:
flattened_vector = nn.flatten_weights_and_biases()
print(flattened_vector)

[0.9398936746504094, 0.3976654977448871, -1.477629453705589, 0.6693226616647363, 0.17562002242794125, 1.002052100670239, 0.4921839629815625, -0.23054713692178888, 1.0134753738362798, 2.035937858273, 1.3194171406306505, -0.2024634440484495, -0.9350963888649291, -1.4935533943250234, 0.192847200465434, -0.4406398297214616, 0.23283755243777504, -1.4660373112985923, -0.40048528187574267, 0.3292305297623279, -0.33046872539328065, -0.6254074273937547, -2.566619306523254, -0.0518371286689409, -0.9199541616068643, 0.770255994405145, -0.8835616679660938, 0.29705918175903145, -0.3099252721040978, 0.32996834461441177, -0.16612142246012893, 0.6565810655321359, 0.7205925284210253, -0.4212116576119616, 2.028733714959952, 0.27294735388558566]


In [142]:
# unflatten_weights_and_biases(flattened_vector, config)

In [143]:
input_data = X_array_norm

nn_init_pred = nn.forward(input_data)

In [144]:
nn_init_pred

array([[0.81141241],
       [0.80994629],
       [0.82078817],
       ...,
       [0.75263485],
       [0.75893058],
       [0.77974506]])

In [145]:
len(nn_init_pred)

1371

In [146]:
def calculate_fitness(neural_network, X, Y, loss_function):
    predictions = neural_network.forward(X)
    # print(predictions[0])
    loss = loss_function.evaluate(predictions.flatten(), Y)
    # print("Loss",loss)
    # print("predictions = ",predictions.flatten())
    # print("len(predictions) = ",len(predictions.flatten()))
    return loss,predictions

loss_function = BinaryCrossEntropy()
initial_fitness,predictions = calculate_fitness(nn, X, Y, loss_function)
print("initial_fitness", initial_fitness)

initial_fitness 0.8151022194901105


In [147]:
def forward_pass(X, Y, W):
    # Rebuild the neural network with the given weights
    position = unflatten_weights_and_biases(W, config)
    # print(position)
    neural_network = NeuralNetwork(config, position=position)

    # Perform forward pass
    predictions = neural_network.forward(X)

    # Calculate loss
    loss = loss_function.evaluate(predictions.flatten(), Y)
    return loss

In [148]:
loss = forward_pass(X, Y, flattened_vector)
print(loss)

0.8151022194901105


In [149]:
def get_accuracy(Y, Y_pred):
    """
    Calcualtes accuracy.
    :param Y: int(N, )
        Correct labels.
    :param Y_pred: int(N, ) | double(N, C)
        Predicted labels of shape(N, ) or (N, C) in case of one-hot vector.
    :return: double
        Accuracy.
    """
    predicted_classes = (Y_pred >= 0.5).astype(int) # Convert probabilities to class labels
    return (Y == predicted_classes).mean()

In [150]:
get_accuracy(Y_array, predictions.flatten())

0.45295404814004375

In [162]:
class Particle:
    """
    Particle is a neural network representing a potential solution.
    """
    def __init__(self, num_dim, x_range, v_range, r1_range, r2_range, r3_range):
        """
        Particle class constructor
        :param num_dim: int
            Number of dimensions.
        :param x_range: tuple(double)
            Range of dimension.
        :param v_range: tuple(double)
            Range of velocity.
        """

        self.x = np.random.uniform(x_range[0], x_range[1], (num_dim, )) # particle position
        self.v = np.random.uniform(v_range[0], v_range[1], (num_dim, )) # particle velocity
        self.pbest = np.inf                                             # personal best fitness
        self.pbestpos = np.zeros((num_dim, ))                           # personal best position
        self.informants_best_position = np.zeros((num_dim, ))           # informants best position
        self.informants = []                                            # particle's informants
        self.r1_range = r1_range                                        # array with min and max range for r1
        self.r2_range = r2_range                                        # array with min and max range for r2
        self.r3_range = r3_range                                        # array with min and max range for r3

    def update_informant_best(self, swarm):
        best_fitness = np.inf
        for informant in self.informants:
            if swarm[informant].pbest < best_fitness:
                best_fitness = swarm[informant].pbest
                self.informants_best_position = swarm[informant].pbestpos.copy()

    def update_velocity(self, global_best_position, alpha, beta, gamma, delta, r1_range, r2_range, r3_range):
        r1 = np.random.uniform(self.r1_range[0], self.r1_range[1])
        r2 = np.random.uniform(self.r2_range[0], self.r3_range[1])
        r3 = np.random.uniform(self.r3_range[0], self.r3_range[1])
        # r1, r2, r3 = np.random.rand(3)  # Random coefficients for stochastic components
        cognitive_component = beta * r1 * (self.pbestpos - self.x)
        social_component = gamma * r2 * (self.informants_best_position - self.x)
        global_component = delta * r3 * (global_best_position - self.x)
        self.v = alpha * self.v + cognitive_component + social_component + global_component

In [166]:
class Swarm:
    """
    The Swarm class is a collection of potential solutions, each represented by a particle.
    """
    def __init__(self, no_particle, num_dim, x_range, v_range, iw_range, c, num_informants, r1_range, r2_range, r3_range):
        """
        Swarm class constructor.
        :param no_particle: int
            Number of particles
        :param num_dim: int
            Number of dimensions.
        :param x_range: tuple(double)
            Range of dimensions.
        :param v_range: tuple(double)
            Range of velocities.
        :param iw_range: tuple(double)
            Range of interia weights.
        :param c: 4-tuple(double)
            c[0] -> cognitive parameter, c[1] -> social parameter, c[2] -> Global weight, c[3] -> Inertia weight
        :param num_informants: int
            Number of informants
        """
        self.p = np.array([Particle(num_dim, x_range, v_range, r1_range, r2_range, r3_range) for i in range(no_particle)])
        self.gbest = np.inf
        self.gbestpos = np.zeros((num_dim, ))
        self.x_range = x_range
        self.v_range = v_range
        self.iw_range = iw_range
        self.c0 = c[0]            # Cognitive weight
        self.c1 = c[1]            # Social weight
        self.c2 = c[2]            # Global weight
        self.c3 = c[3]            # Inertia weight
        self.num_dim = num_dim    # Number of dimensions, in this case the total number of weights & biases
        self.num_informants = num_informants
        self.assign_informants()

    def print_informants(self):
        """
        Function prints the informants of every particle.
        """
        for i, particle in enumerate(self.p):
            # Print the particle's index and its informants
            print(f"Particle {i} informants: {particle.informants}")

    def assign_informants(self):
        """
        Function assigns informants to every particle
        """
        for i, particle in enumerate(self.p):
            informants = set()
            # add informants until they are num_informants in informants set
            while len(informants) < self.num_informants:
                # Randomly select a potential informant
                possible_informant = np.random.randint(0, len(self.p))
                # if selected informant is not the particle itself, add it to set
                if possible_informant != i:
                    informants.add(possible_informant)
            particle.informants = np.array(list(informants))

    def optimize(self, function, X, Y,  print_step,  iter):
        """
        Function used to start optimization.
        :param function: function
            Function to be optimized
        :param X: input data
            Used in forward pass.
        :param Y: target class
            Used to calculate loss.
        :param print_step: int
            Step for printing
        :param iter: int
            Number of iterations.
        """
        for i in range(iter):
            for particle in self.p:
                # print("particle.x",particle.x)
                fitness = function(X, Y, particle.x)
                # print("fitness",fitness)
                # print("particle.pbest",particle.pbest)

                if fitness < particle.pbest:
                    particle.pbest = fitness
                    particle.pbestpos = particle.x.copy()

                if fitness < self.gbest:
                    self.gbest = fitness
                    self.gbestpos = particle.x.copy()

            for particle in self.p:
                # update informants best
                particle.update_informant_best(self.p)
                # update particle velocity
                particle.update_velocity(self.gbestpos, self.c3, self.c0, self.c1, self.c2, r1_range, r2_range, r3_range)
                # update particle position
                particle.x = particle.x +  particle.v

            if i % print_step == 0:
                print('iteration#: ', i+1,  ' loss: ', fitness)

        print("global best loss: ", self.gbest)

    def get_best_solution(self):
        '''

        :return: array of parameters/weights.
        '''
        return self.gbestpos

In [167]:
def get_num_dim(configuration):
  total_weights = 0
  total_biases = 0

  # The number of nodes in the previous layer, initially the input layer
  prev_nodes = configuration[0]

  # Loop through each layer (excluding the input layer)
  for layer in configuration[1:]:
      # Extract the number of nodes in the current layer
      nodes = layer[0]

      # Calculate weights and biases for the current layer
      weights = prev_nodes * nodes
      biases = nodes

      # Add to total weights and biases
      total_weights += weights
      total_biases += biases

      # Update prev_nodes for the next iteration
      prev_nodes = nodes

  # Output the total number of dimensions
  total_dimensions = total_weights + total_biases
  return total_dimensions

In [173]:
if __name__ == '__main__':
    no_solution = 10
    no_dim = get_num_dim(config)
    w_range = (0.0, 1.0)
    lr_range = (0.0, 1.0)
    iw_range = (0, 1)  # iw -> inertial weight
    c = (0.5, 0.3, 0.2, 0.9)  # c[0] -> cognitive factor, c[1] -> global factor,  c[2] -> social factor, c[3] -> inertial weight
    num_informants = 5
    r1_range = [0,1]
    r2_range = [0,1]
    r3_range = [0,1]

    s = Swarm(no_solution, no_dim, w_range, lr_range, iw_range, c, num_informants, r1_range, r2_range, r3_range)
    s.print_informants()

    # Train:Test Split
    test_size = 0.2  # User defined split ratio
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=test_size, random_state=42)

    s.optimize(forward_pass, X_train, Y_train, 100, 400)
    W = s.get_best_solution()

    # Perform forward pass with the best solution (weights)
    best_position = unflatten_weights_and_biases(W, config)
    best_nn = NeuralNetwork(config, position=best_position)

    Y_pred = best_nn.forward(X_train).flatten()
    Y_pred2 = best_nn.forward(X_test).flatten()

    # Calculate and print accuracy
    accuracy = get_accuracy(Y_train.to_numpy().flatten(), Y_pred)
    print("Train Accuracy: %.3f" % accuracy)

    # Calculate and print accuracy
    accuracy = get_accuracy(Y_test.to_numpy().flatten(), Y_pred2)
    print("Test Accuracy: %.3f" % accuracy)


Particle 0 informants: [1 4 5 7 9]
Particle 1 informants: [3 4 5 8 9]
Particle 2 informants: [4 5 6 7 9]
Particle 3 informants: [1 2 6 7 8]
Particle 4 informants: [0 3 5 8 9]
Particle 5 informants: [0 2 3 6 7]
Particle 6 informants: [2 3 5 7 8]
Particle 7 informants: [0 1 3 4 9]
Particle 8 informants: [0 2 3 6 7]
Particle 9 informants: [1 2 6 7 8]
iteration#:  1  loss:  1.3812649026249604
iteration#:  101  loss:  0.265247128723648
iteration#:  201  loss:  0.2636930642958968
iteration#:  301  loss:  0.2635440222809964
global best loss:  0.26351295210599773
Train Accuracy: 0.920
Test Accuracy: 0.942
